---
title: 'Tidy Tuesday #3'
author: "Nicole Higgins"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
# You may want to comment this out at first so you see important messages and warnings
#knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
theme_set(theme_minimal())       # My favorite ggplot() theme :)
```

```{r}
# Read in the data for the week
beyonce_lyrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/beyonce_lyrics.csv')
taylor_swift_lyrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/taylor_swift_lyrics.csv')
sales <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/sales.csv')
charts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/charts.csv')
```


```{r, warning=FALSE}
sales %>%
  filter(country == "US") %>%
  separate(released, into = c("released", "junk"), sep = "\\(") %>%
  group_by(artist) %>%
  mutate(released = mdy(released)) %>%
  ggplot(aes(x = released, 
             y = sales)) +
  geom_line() +
  geom_point(aes(color = label), size = 3) +
  facet_wrap(vars(artist)) +
  labs(title = "Bey and T Swift's US Sales by Record Label",
       color = "Label") +
  theme(plot.background = element_rect(fill = "#b6d4c8"),
        axis.title = element_blank(),
        plot.title = element_text(size = "15", face = "bold"))
```


